set nocompatible
set t_Co=256
filetype off

" Setup Vundler...
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
" required!
Plugin 'gmarik/Vundle.vim'

" Github bundles
" Interface
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'bogado/file-line'
Plugin 'sudo.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'rstacruz/sparkup'
Plugin 'scrooloose/nerdcommenter'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'Raimondi/delimitMate'
Plugin 'Valloric/YouCompleteMe' " Vim 7.4+. Extra build step: ./install.sh --clang-completer
Plugin 'ryanss/vim-hackernews'

" JavaScript
Plugin 'pangloss/vim-javascript'
Plugin 'marijnh/tern_for_vim' " Extra build step. npm install (use system npm)
Plugin 'kchmck/vim-coffee-script'

" Templates / Markup
Plugin 'slim-template/vim-slim'
Plugin 'mustache/vim-mustache-handlebars'

" CSS
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'wavded/vim-stylus'
Plugin 'groenewege/vim-less'

" Git
Plugin 'tpope/vim-fugitive'

" Colorschemes
Plugin 'altercation/vim-colors-solarized'
Plugin 'tomasr/molokai'
Plugin 'nanotech/jellybeans.vim'
Plugin 'Lokaltog/vim-distinguished'
Plugin 'tpope/vim-vividchalk'
Plugin 'noahfrederick/Hemisu'
Plugin 'morhetz/gruvbox'
Plugin 'Zenburn'
Plugin 'Wombat'
Plugin 'Guardian'
Plugin 'wombat256.vim'

call vundle#end()
" Plugins that are marked for removal:
"Plugin 'jelera/vim-javascript-syntax'
"Plugin 'vim-scripts/JavaScript-Indent'
"Plugin 'Shougo/neocomplcache'
"Plugin 'Shougo/neosnippet'
"Plugin 'plasticboy/vim-markdown'
"Plugin 'jistr/vim-nerdtree-tabs'
"Plugin 'vim-scripts/VOoM'
"Plugin 'bufexplorer'

" Vundle requires that this come AFTER plugins are declared:
syntax enable
filetype plugin indent on

" Fix backspace when on the terminal...
set backspace=2

" Turn on line numbering. Turn it off with 'set nonu'
set nu

" Indent automatically depending on filetype
set autoindent

" 'Smart' case insensitive search
set scs

" Show command in the last line of the screen
set sc

" Set tabs to four spaces + smart indentation
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

" Add row / columnn information
set ruler

" Highlight search
set hls

" Wrap text instead of being on one line
set lbr

" Hide the annoying omnicomplete preview window
set completeopt-=preview


" Plugin-specific settings...
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)|node_modules|bower_components$',
  \ }

" Set personalized key settings...
let NERDComInsertMap='<c-c>'
let mapleader=","

" Configure Syntastic...
let g:syntastic_check_on_open=1
let g:syntastic_enable_signs=1
let g:syntastic_error_symbol='✗'
let g:syntastic_warning_symbol='⚠'

let g:syntastic_mode_map={ 'mode': 'active',
                         \ 'active_filetypes': ['javascript', 'css'],
                         \ 'passive_filetypes': ['java', 'html'] }

" Configure vim-indent-guides
let g:indent_guides_enable_on_vim_startup=1
let g:indent_guides_auto_colors=0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=238
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=237

" Configure YouCompleteMe
let g:ycm_add_preview_to_completeopt=0

" This allows the current search to be cleared with <F3>
nnoremap <F3> :let @/ = ""<CR>
set whichwrap+=<,>,h,l,[,]

" Change colorscheme from default to zenburn
set background=dark
let g:solarized_termcolors=256
try
  colorscheme zenburn
catch
endtry

" Simplify activating and deactivating 'hex mode'
map <Leader>hx :%!xxd<CR>
map <Leader>xh :%!xxd -r<CR>

" Highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Disable arrow keys in normal / visual / select modes:
noremap  <Up> ""
noremap  <Down> ""
noremap  <Left> ""
noremap  <Right> ""


