set nocompatible
set t_Co=256

" Turn on line numbering. Turn it off with 'set nonu'
set nu

" Fix backspace when on the terminal...
set backspace=2

" Set plugin / syntax required options...
filetype off
filetype plugin on
syntax on

" Setup Vundler...
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

" Github bundles
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/syntastic'
Bundle 'plasticboy/vim-markdown'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'rstacruz/sparkup'
Bundle 'pangloss/vim-javascript'
Bundle 'tpope/vim-fugitive'
Bundle 'wavded/vim-stylus'
Bundle 'cakebaker/scss-syntax.vim'
Bundle 'kchmck/vim-coffee-script'
Bundle 'altercation/vim-colors-solarized'
Bundle 'tomasr/molokai'
Bundle 'nanotech/jellybeans.vim'
Bundle 'Lokaltog/vim-distinguished'
Bundle 'tpope/vim-vividchalk'
Bundle 'noahfrederick/Hemisu'
Bundle 'morhetz/gruvbox'
Bundle 'bogado/file-line'
Bundle 'jistr/vim-nerdtree-tabs'
Bundle 'Shougo/neocomplcache.git'
Bundle 'Shougo/neosnippet.git'

" Vim-scripts bundles
Bundle 'Zenburn'
Bundle 'Wombat'
Bundle 'wombat256.vim'

" Plugin-specific settings...

" Set personalized key settings...
let NERDComInsertMap='<c-c>'
let mapleader=","

" Configure Syntastic...
let g:syntastic_check_on_open=1
let g:syntastic_enable_signs=1
let g:syntastic_error_symbol='✗'
let g:syntastic_warning_symbol='⚠'

let g:syntastic_mode_map={ 'mode': 'active',
                         \ 'active_filetypes': ['javascript', 'css', 'html'],
                         \ 'passive_filetypes': ['java'] }

" Neocomplecache
let g:neocomplcache_enable_at_startup = 1
let g:neocomplcache_enable_smart_case = 1
let g:neocomplcache_enable_camel_case_completion = 1
let g:neocomplcache_enable_underbar_completion = 1
let g:neocomplcache_min_syntax_length = 3

inoremap <expr><CR>  neocomplcache#smart_close_popup() . "\<CR>"
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

inoremap <expr><C-h>  neocomplcache#smart_close_popup() . "\<C-h>"
inoremap <expr><BS>  neocomplcache#smart_close_popup() . "\<C-h>"
inoremap <expr><C-y>  neocomplcache#close_popup()
inoremap <expr><C-e>  neocomplcache#cancel_popup()

autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Neosnippet
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)

" Automatically close preview window when popup closes
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" This allows the current search to be cleared with <F3>
nnoremap <F3> :let @/ = ""<CR>
set whichwrap+=<,>,h,l,[,]

" Indent automatically depending on filetype
filetype indent on
set autoindent

" 'Smart' case insensitive search
set scs
" Show command in the last line of the screen
set sc

" Set tabs to four spaces + smart indentation
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

" Add row / columnn information
set ruler

" Higlhight search
set hls

" Wrap text instead of being on one line
set lbr

" Change colorscheme from default to zenburn
set background=dark
let g:solarized_termcolors=256
try
  colorscheme zenburn
catch
endtry

" Highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()
